[package]
name = "spherical_voronoi"
version = "0.1.0"
authors = ["Roman Akberov <r.k.akberov@gmail.com>"]

[dependencies]
cgmath = "*"
fnv = "*"
id = {path = "../id"}
diagram = {path = "../diagram"}
