[package]
name = "spherical_voronoi"
version = "0.1.0"
authors = ["Roman Akberov <r.k.akberov@gmail.com>"]

[dependencies]
cgmath = "*"
diagram = {git = "https://github.com/RomanAkberov/diagram"}
ideal = {git = "https://github.com/RomanAkberov/ideal"}
