[package]
name = "spherical_voronoi"
version = "0.1.0"
authors = ["Roman Akberov <r.k.akberov@gmail.com>"]

[dependencies]
id = {git = "https://github.com/RomanAkberov/id"}
diagram = {git = "https://github.com/RomanAkberov/diagram"}
cgmath = "*"